platform :ios,'5.0'

pod 'RestKit', :head

pod 'JSONKit', :head

pod 'BlocksKit', :head

pod 'SDWebImage', :head

pod 'MagicalRecord', :head

pod 'Reachability', :head

pod 'MBProgressHUD', :head

pod 'Appirater', :head
